/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

#define PLUGIN 	"End Round Sounds"
#define VERSION "2.2.0"
#define AUTHOR 	"Google Gemini, kwpd"

new Array:g_aSounds_download
new pcvar_next
new pcvar_randon_music
new pcvar_maps

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_logevent("Round_End", 2, "1=Round_End")
	pcvar_next = register_cvar("next_music", "0")
	pcvar_randon_music = register_cvar("music_random", "1")
	pcvar_maps = register_cvar("next_maps_music", "1")
	set_musict_default()
}

public set_musict_default()
{
	set_cvar_num("next_music", 0)
	set_cvar_num("music_random", 1)
	
	return PLUGIN_CONTINUE
}

public plugin_precache()
{
	g_aSounds_download = ArrayCreate(64)
	
	pcvar_maps = register_cvar("next_maps_music", "1")
	new current_num = get_pcvar_num(pcvar_maps)
	
	if (current_num < 1 || current_num > 3)
		current_num = 1
	
	new configsdir[128], file_download[192]
	get_configsdir(configsdir, charsmax(configsdir))
	
	// Precargar las 3 listas existentes (1, 2 y 3)
	for (new i = 1; i <= 3; i++)
	{
		formatex(file_download, charsmax(file_download), "%s/EndRoundSounds/%dnext_win.txt", configsdir, i)
		
		// Solo guardamos en la RAM (Array) la lista del mapa actual (current_num)
		new bool:es_mapa_actual = (i == current_num)
		
		cargar_y_precargar_sonidos(file_download, g_aSounds_download, es_mapa_actual)
	}
}

stock cargar_y_precargar_sonidos(const file_path[], Array:sound_array, bool:guardar_en_memoria)
{
	if (!file_exists(file_path))
		return
	
	new file_handle = fopen(file_path, "rt")
	if (!file_handle)
		return
	
	new song_line[64], song_dir_full[128], song_dir_precache[128]
	
	while (!feof(file_handle))
	{
		fgets(file_handle, song_line, charsmax(song_line))
		trim(song_line)
		
		// Ignorar líneas vacías o comentarios
		if (song_line[0] == EOS || song_line[0] == ';' || song_line[0] == '#')
			continue
		
		formatex(song_dir_full, charsmax(song_dir_full), "sound/EndRoundSounds/%s", song_line)
		
		if (file_exists(song_dir_full))
		{
			// Precarga universal de audio
			if (containi(song_line, ".mp3") != -1)
			{
				precache_generic(song_dir_full)
			}
			else if (containi(song_line, ".wav") != -1)
			{
				formatex(song_dir_precache, charsmax(song_dir_precache), "EndRoundSounds/%s", song_line)
				precache_sound(song_dir_precache)
			}
			
			// Si pertenece a la lista actual, se almacena para reproducir en este mapa
			if (guardar_en_memoria && sound_array != Invalid_Array)
			{
				ArrayPushString(sound_array, song_line)
			}
		}
	}
	
	fclose(file_handle)
}

public plugin_end()
{
	new num = get_pcvar_num(pcvar_maps)
	switch (num)
	{
		case 1: num = 2
		case 2: num = 3
		default: num = 1 // Si es 3 (o cualquier otro valor fuera de rango), vuelve a 1
	}
	set_cvar_num("next_maps_music", num)
	return PLUGIN_CONTINUE
}

public p_music_win()
{
	new archivoDir[128];
	get_configsdir(archivoDir, charsmax(archivoDir));
	
	// Selección del archivo de configuración según el mapa actual
	switch(get_pcvar_num(pcvar_maps))
	{
		case 1: format(archivoDir, charsmax(archivoDir), "%s/EndRoundSounds/1next_win.txt", archivoDir);
		case 2: format(archivoDir, charsmax(archivoDir), "%s/EndRoundSounds/2next_win.txt", archivoDir);
		case 3: format(archivoDir, charsmax(archivoDir), "%s/EndRoundSounds/3next_win.txt", archivoDir);
		default: format(archivoDir, charsmax(archivoDir), "%s/EndRoundSounds/1next_win.txt", archivoDir);
	}
	
	// Obtenemos el valor actual del cvar y calculamos la línea exacta (restando 1 porque read_file empieza en 0)
	new current_index = get_pcvar_num(pcvar_next) - 1;
	
	if (current_index >= 0)
	{
		new texto[128], len;
		
		// read_file lee directamente la línea solicitada de forma eficiente
		if (read_file(archivoDir, current_index, texto, charsmax(texto), len) && len > 0)
		{
			trim(texto);
			// Limpiamos espacios o saltos de línea sobrantes
			
			// Obtenemos únicamente a los jugadores reales conectados (excluyendo bots y HLTV)
			new players[32], pnum;
			get_players(players, pnum, "ch");
			
			for (new i = 0; i < pnum; i++)
			{
				new id = players[i];
				client_cmd(id, "mp3 stop; mp3 play sound/EndRoundSounds/%s", texto);
			}
		}
	}
	
	return PLUGIN_CONTINUE;
}

public Round_End()
{
	// Modo Aleatorio (Random)
	if (get_pcvar_num(pcvar_randon_music))
	{
		// Selecciona un número al azar del 1 al 30 de forma directa y limpia
		new rand = random_num(1, 30);
		
		set_cvar_num("music_random", 0);
		set_cvar_num("next_music", rand);
		
		p_music_win();
		return PLUGIN_CONTINUE;
	}

	// Modo Secuencial del 1 al 30
	new current = get_pcvar_num(pcvar_next);
	
	if (current >= 1 && current < 30)
	{
		set_cvar_num("next_music", current + 1);
	}
	else
	{
		// Si llega a 30 o tiene un valor inválido, reinicia la secuencia en 1
		set_cvar_num("next_music", 1);
	}
	
	p_music_win();
	return PLUGIN_CONTINUE;
}
